### ISSUE TITLE
Support "Enable CORS"

### ISSUE THREAD

**Issue by k-nishijima** [horike37/simple-api-gateway#1]
createするときに、同時にOPTIONSメソッドも勝手に作ってCORS有効にしておく、みたいなのでいいだろうか（CORS不要な場合ってあるけど。。。）

**Comment by horike37** [comment]
そうっすね。「Corsの設定します？」の2択で選択させて、yes選べばOPTIONSメソッド勝手に作って有効化するって形でいいと思います。ヘッダの設定もマネジメントコンソールでCors有効化した時と同じ設定で。

**Comment by k-nishijima** [comment]
👍 やっとく

**Comment by horike37** [comment]
あざっす！

**Comment by k-nishijima** [comment]
1つ分からないな〜。
'integration.response.header.Access-Control-Allow-Origin': '_'
って指定しても
"'_'"
でも、その他いろいろ試してみたんですが
Invalid mapping expression specified: integration.response.header.Access-Control-Allow-Origin
で怒られちゃう。

JSONとして流すときに上手いエスケープをして上げる必要があるのかな。。。

**Comment by k-nishijima** [comment]
あ、上のアスタリスクが消えちゃってる。

>  'integration.response.header.Access-Control-Allow-Origin': "'*'"

で出るかな。

**Comment by horike37** [comment]
おっ、どのへんです？
作られてるソース直接見せてもらってもいいです？

**Comment by k-nishijima** [comment]
例えばこんな感じでAccess-Control-Allow-Originヘッダに

> '*'

を渡したいだけなんだけど上手く行かず。
色んなパターンを試して疲れてきましたorz

> ```
> let params = {
>       httpMethod: settings.method,
>       resourceId: settings.resource.id,
>       restApiId : settings.api_id,
>       statusCode: '200',
>       responseTemplates:{'application/json':''}
>     }
>   if (settings['enableCORS']) {
>       params['responseParameters'] = {
>           'integration.response.header.Access-Control-Allow-Origin': '"*"'
>       }
>   }
> return apigateway.putIntegrationResponse(params).promise()
> ```

**Comment by horike37** [comment]
ほんとっすね。
以下のコードで試してみたけど

```
let params = {
      httpMethod: settings.method,
      resourceId: settings.resource.id,
      restApiId : settings.api_id,
      statusCode: '200',
      responseTemplates:{'application/json':''},
      responseParameters:{
        "method.response.header.Access-Control-Allow-Headers": "\'Content-Type,X-Amz-Date,Authorization,X-Api-Key,Cache-Control|'",
        "method.response.header.Access-Control-Allow-Methods": "\'*\'",
        "method.response.header.Access-Control-Allow-Origin": "\'*\'"
      }
    }
return apigateway.putIntegrationResponse(params).promise()
```

以下のエラーが返ってきた。。

```
error: BadRequestException: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression parameter specified: method.response.header.Access-Control-Allow-Methods]
```

こちらでも色々見てみます。Serverless Frameworkでは、JSONにCORSの設定すればローカルからの設定は可能なので根本的にできないってこてゃないはずなので。。

**Comment by k-nishijima** [comment]
この辺ですよね〜。
https://github.com/joostfarla/serverless-cors-plugin/blob/develop/src/index.js#L57

このエスケープは試したんだけど、だめだったんだよな・・。

**Comment by k-nishijima** [comment]
あ、スミマセン設定は一応通ってるみたいですが、まだ足りないパラメータがあるのかも？
JavaScriptクライアントから上手く呼べない・・・。

**Comment by k-nishijima** [comment]
プルリクの方にコメントつけちゃった。
一応手元ではなんとなく動きました。

**Comment by horike37** [comment]
プルリク問題なさそうだったので、バージョン0.1.5にあげて取り込んでおきました。
https://www.npmjs.com/package/simple-api-gateway

ありがとうございました！
